name: deploy
env: 
  DEPLOY_PACKAGE_NAME: "DEPLOY-VER-${{github.sha}}"
  NODE_VERSION: 14
on: release

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/checkout@v2
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: ls dist
      run: ls -ltr ./dist
    - name: transfer package.json
      uses: appleboy/scp-action@master
      with:
          host: ${{secrets.HOST}}
          username: root
          passphrase: ${{secrets.PASSPHRASE}}
          key: ${{secrets.PRIVATE_KEY}}
          source: "dist/package.json"
          target: "test"
          rm: "true"
