name: deploy
env: 
  DEPLOY_PACKAGE_NAME: "DEPLOY-VER-${{github.sha}}"
  NODE_VERSION: 14
on: release

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/checkout@v2
    - name: npm install and build
      run: |
        npm install
        npm run build
        
  transfer-files: 
    runs-on: ubuntu-latest
    needs: [build]
    
    steps: 
    - name: ls -a
      run: ls -a
    - name: transfer package.json
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSPHRASE }}
          source: "./dist/package.json"
          target: "./baby_app/"
